# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app_design1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1282, 722)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.centralwidget.setFont(font)
        self.centralwidget.setStyleSheet("background-color: #121212;")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pomodoro_timer_frame = QtWidgets.QFrame(self.centralwidget)
        self.pomodoro_timer_frame.setMinimumSize(QtCore.QSize(480, 720))
        self.pomodoro_timer_frame.setMaximumSize(QtCore.QSize(480, 16777215))
        self.pomodoro_timer_frame.setBaseSize(QtCore.QSize(480, 720))
        self.pomodoro_timer_frame.setStyleSheet("#pomodoro_timer_frame {\n"
"border: none;\n"
"border-right: 2px solid #2a2929;\n"
"}")
        self.pomodoro_timer_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.pomodoro_timer_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pomodoro_timer_frame.setObjectName("pomodoro_timer_frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.pomodoro_timer_frame)
        self.gridLayout_3.setContentsMargins(30, 30, 30, 30)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.responsive_frame = QtWidgets.QFrame(self.pomodoro_timer_frame)
        self.responsive_frame.setStyleSheet("#responsive_frame {\n"
"border-radius: 20px;\n"
"background-color: #2a2929;\n"
"}\n"
"\n"
"\n"
"")
        self.responsive_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.responsive_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.responsive_frame.setObjectName("responsive_frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.responsive_frame)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pomodoro_content_frame = QtWidgets.QFrame(self.responsive_frame)
        self.pomodoro_content_frame.setMaximumSize(QtCore.QSize(360, 640))
        self.pomodoro_content_frame.setStyleSheet("#pomodoro_content_frame {\n"
"border-radius: 20px;\n"
"background-color: #2a2929;\n"
"}\n"
"\n"
"")
        self.pomodoro_content_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.pomodoro_content_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pomodoro_content_frame.setObjectName("pomodoro_content_frame")
        self.play_pushButton = QtWidgets.QPushButton(self.pomodoro_content_frame)
        self.play_pushButton.setGeometry(QtCore.QRect(120, 510, 120, 50))
        self.play_pushButton.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    border-radius: 20px;\n"
"    color: #f0f0f0;\n"
"    background-color: #5647ae;\n"
"    padding-left: 20px;\n"
"    padding-right: 20px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #483d94;\n"
"}\n"
"")
        self.play_pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../img/play-fill.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.play_pushButton.setIcon(icon)
        self.play_pushButton.setIconSize(QtCore.QSize(30, 30))
        self.play_pushButton.setObjectName("play_pushButton")
        self.change_modus_label = QtWidgets.QLabel(self.pomodoro_content_frame)
        self.change_modus_label.setGeometry(QtCore.QRect(30, 40, 301, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(20)
        self.change_modus_label.setFont(font)
        self.change_modus_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.change_modus_label.setStyleSheet("#change_modus_label {\n"
"    background-color: #2a2929;\n"
"    color: white;\n"
"    text-align: center;\n"
"    qproperty-alignment: \'AlignCenter\';\n"
"}\n"
"\n"
"")
        self.change_modus_label.setObjectName("change_modus_label")
        self.time_bar_base_frame = QtWidgets.QFrame(self.pomodoro_content_frame)
        self.time_bar_base_frame.setGeometry(QtCore.QRect(30, 140, 300, 300))
        self.time_bar_base_frame.setMinimumSize(QtCore.QSize(300, 300))
        self.time_bar_base_frame.setStyleSheet("#time_bar_base_frame{\n"
"    background-color: #2a2929;\n"
"}")
        self.time_bar_base_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.time_bar_base_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.time_bar_base_frame.setObjectName("time_bar_base_frame")
        self.time_bar_bg_frame = QtWidgets.QFrame(self.time_bar_base_frame)
        self.time_bar_bg_frame.setGeometry(QtCore.QRect(0, 0, 300, 300))
        self.time_bar_bg_frame.setStyleSheet("QFrame {\n"
"    background-color: rgba(42, 42, 42, 100);\n"
"    border-radius: 150px;\n"
"}\n"
"")
        self.time_bar_bg_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.time_bar_bg_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.time_bar_bg_frame.setObjectName("time_bar_bg_frame")
        self.time_bar_frame = QtWidgets.QFrame(self.time_bar_base_frame)
        self.time_bar_frame.setGeometry(QtCore.QRect(0, 0, 301, 301))
        self.time_bar_frame.setStyleSheet("QFrame {\n"
"    background-color: qconicalgradient(cx:0.5, cy:0.5, angle:90, stop:0.749 rgba(0, 0, 0, 0), stop:0.75 rgba(255, 255, 255, 255));\n"
"    border-radius: 150px\n"
"}")
        self.time_bar_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.time_bar_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.time_bar_frame.setObjectName("time_bar_frame")
        self.time_bar_container_frame = QtWidgets.QFrame(self.time_bar_base_frame)
        self.time_bar_container_frame.setGeometry(QtCore.QRect(15, 15, 270, 270))
        self.time_bar_container_frame.setStyleSheet("QFrame {\n"
"    background-color: #2a2929;\n"
"    border-radius: 130px;\n"
"}")
        self.time_bar_container_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.time_bar_container_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.time_bar_container_frame.setObjectName("time_bar_container_frame")
        self.timer_label = QtWidgets.QLabel(self.time_bar_base_frame)
        self.timer_label.setGeometry(QtCore.QRect(0, 120, 301, 60))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(36)
        self.timer_label.setFont(font)
        self.timer_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.timer_label.setStyleSheet("#timer_label {\n"
"    background-color: rgba(42, 41, 41, 0);\n"
"    color: white;\n"
"    text-align: center;\n"
"    qproperty-alignment: \'AlignCenter\';\n"
"}\n"
"\n"
"")
        self.timer_label.setObjectName("timer_label")
        self.gridLayout_2.addWidget(self.pomodoro_content_frame, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.responsive_frame, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.pomodoro_timer_frame)
        self.managment_tool_frame = QtWidgets.QFrame(self.centralwidget)
        self.managment_tool_frame.setMinimumSize(QtCore.QSize(800, 720))
        self.managment_tool_frame.setStyleSheet("#managment_tool_frame {\n"
"border: none;\n"
"border-left: 2px solid #2a2929;\n"
"}")
        self.managment_tool_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.managment_tool_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.managment_tool_frame.setObjectName("managment_tool_frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.managment_tool_frame)
        self.gridLayout_4.setContentsMargins(30, 30, 30, 30)
        self.gridLayout_4.setSpacing(30)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.btn_content_frame = QtWidgets.QFrame(self.managment_tool_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_content_frame.sizePolicy().hasHeightForWidth())
        self.btn_content_frame.setSizePolicy(sizePolicy)
        self.btn_content_frame.setMaximumSize(QtCore.QSize(16777215, 150))
        self.btn_content_frame.setStyleSheet("#btn_content_frame {\n"
"border-radius: 20px;\n"
"background-color: #2a2929;\n"
"}\n"
"\n"
"")
        self.btn_content_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.btn_content_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.btn_content_frame.setObjectName("btn_content_frame")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.btn_content_frame)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.btn_allign_frame = QtWidgets.QFrame(self.btn_content_frame)
        self.btn_allign_frame.setMinimumSize(QtCore.QSize(500, 0))
        self.btn_allign_frame.setStyleSheet("background-color: rgba(0,0,0,0);")
        self.btn_allign_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.btn_allign_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.btn_allign_frame.setObjectName("btn_allign_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.btn_allign_frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Task_pushButton = QtWidgets.QPushButton(self.btn_allign_frame)
        self.Task_pushButton.setMinimumSize(QtCore.QSize(120, 50))
        self.Task_pushButton.setMaximumSize(QtCore.QSize(120, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Task_pushButton.setFont(font)
        self.Task_pushButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Task_pushButton.setStyleSheet("QPushButton{\n"
"border: none;\n"
"border-radius: 20px;\n"
"color: #f0f0f0;\n"
"background-color: #5647ae;\n"
"}")
        self.Task_pushButton.setObjectName("Task_pushButton")
        self.horizontalLayout_2.addWidget(self.Task_pushButton)
        self.statistics_pushButton = QtWidgets.QPushButton(self.btn_allign_frame)
        self.statistics_pushButton.setMaximumSize(QtCore.QSize(120, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.statistics_pushButton.setFont(font)
        self.statistics_pushButton.setStyleSheet("QPushButton {\n"
"    border: solid;\n"
"    border-color: #5647ae;\n"
"    border-width: 3px;\n"
"    border-radius: 20px;\n"
"    color: #f0f0f0;\n"
"    background-color: rgba(0,0,0,0);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgba( 86, 71, 174, 0.16)\n"
"}")
        self.statistics_pushButton.setObjectName("statistics_pushButton")
        self.horizontalLayout_2.addWidget(self.statistics_pushButton)
        self.settings_pushButton = QtWidgets.QPushButton(self.btn_allign_frame)
        self.settings_pushButton.setMaximumSize(QtCore.QSize(120, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.settings_pushButton.setFont(font)
        self.settings_pushButton.setStyleSheet("QPushButton{\n"
"border: solid ;\n"
"border-color: #5647ae;\n"
"border-width: 3px;\n"
"border-radius: 20px;\n"
"color: #f0f0f0;\n"
"background-color: rgba(0,0,0,0);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgba( 86, 71, 174, 0.16)\n"
"}")
        self.settings_pushButton.setObjectName("settings_pushButton")
        self.horizontalLayout_2.addWidget(self.settings_pushButton)
        self.gridLayout_6.addWidget(self.btn_allign_frame, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.gridLayout_4.addWidget(self.btn_content_frame, 0, 0, 1, 1)
        self.content_frame = QtWidgets.QFrame(self.managment_tool_frame)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.content_frame.setFont(font)
        self.content_frame.setStyleSheet("#content_frame {\n"
"border-radius: 20px;\n"
"background-color: #2a2929;\n"
"\n"
"}\n"
"")
        self.content_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.content_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content_frame.setObjectName("content_frame")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.content_frame)
        self.gridLayout_11.setContentsMargins(9, -1, -1, -1)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.content_stackedWidget = QtWidgets.QStackedWidget(self.content_frame)
        self.content_stackedWidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.content_stackedWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.content_stackedWidget.setStyleSheet("background-color: #2a2929;\n"
"\n"
"\n"
"QToolButton#qt_stackwidget_qtoolbutton {\n"
"    width: 0;\n"
"    height: 0;\n"
"}")
        self.content_stackedWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.content_stackedWidget.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content_stackedWidget.setObjectName("content_stackedWidget")
        self.task_managment_content_WidgetPage = QtWidgets.QWidget()
        self.task_managment_content_WidgetPage.setObjectName("task_managment_content_WidgetPage")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.task_managment_content_WidgetPage)
        self.gridLayout_5.setContentsMargins(30, 30, 30, 30)
        self.gridLayout_5.setSpacing(30)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.save_pushButton = QtWidgets.QPushButton(self.task_managment_content_WidgetPage)
        self.save_pushButton.setMinimumSize(QtCore.QSize(120, 50))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.save_pushButton.setFont(font)
        self.save_pushButton.setStyleSheet("QPushButton{\n"
"border: none;\n"
"border-radius: 20px;\n"
"color: #f0f0f0;\n"
"background-color: #5647ae;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #483d94;\n"
"}\n"
"")
        self.save_pushButton.setObjectName("save_pushButton")
        self.gridLayout_5.addWidget(self.save_pushButton, 1, 1, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.task_managment_content_WidgetPage)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("\n"
"border: solid ;\n"
"border-color: #5647ae;\n"
"border-width: 3px;\n"
"border-radius: 20px;\n"
"color: #f0f0f0;\n"
"background-color: rgba(0,0,0,0);\n"
"")
        self.lineEdit.setText("")
        self.lineEdit.setCursorPosition(0)
        self.lineEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_5.addWidget(self.lineEdit, 1, 0, 1, 1)
        self.clear_pushButton = QtWidgets.QPushButton(self.task_managment_content_WidgetPage)
        self.clear_pushButton.setMinimumSize(QtCore.QSize(120, 50))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.clear_pushButton.setFont(font)
        self.clear_pushButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.clear_pushButton.setStyleSheet("QPushButton{\n"
"border: solid ;\n"
"border-color: #5647ae;\n"
"border-width: 3px;\n"
"border-radius: 20px;\n"
"color: #f0f0f0;\n"
"background-color: rgba(0,0,0,0);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgba( 86, 71, 174, 0.16)\n"
"}")
        self.clear_pushButton.setObjectName("clear_pushButton")
        self.gridLayout_5.addWidget(self.clear_pushButton, 1, 2, 1, 1)
        self.checkbox_frame = QtWidgets.QFrame(self.task_managment_content_WidgetPage)
        self.checkbox_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.checkbox_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.checkbox_frame.setObjectName("checkbox_frame")
        self.gridLayout_5.addWidget(self.checkbox_frame, 0, 0, 1, 3)
        self.content_stackedWidget.addWidget(self.task_managment_content_WidgetPage)
        self.statistics_content_WidgetPage = QtWidgets.QWidget()
        self.statistics_content_WidgetPage.setObjectName("statistics_content_WidgetPage")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.statistics_content_WidgetPage)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.day_week_month_label = QtWidgets.QLabel(self.statistics_content_WidgetPage)
        self.day_week_month_label.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(16)
        self.day_week_month_label.setFont(font)
        self.day_week_month_label.setStyleSheet("color: white;")
        self.day_week_month_label.setObjectName("day_week_month_label")
        self.gridLayout_12.addWidget(self.day_week_month_label, 0, 0, 1, 1)
        self.move_backward_pushButton = QtWidgets.QPushButton(self.statistics_content_WidgetPage)
        self.move_backward_pushButton.setStyleSheet("QPushButton {\n"
"    border: solid;\n"
"    border-color: #5647ae;\n"
"    border-width: 3px;\n"
"    border-radius: 15px;\n"
"    color: #f0f0f0;\n"
"    background-color: rgba(0,0,0,0);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgba( 86, 71, 174, 0.16)\n"
"}")
        self.move_backward_pushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../img/backward-fill.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.move_backward_pushButton.setIcon(icon1)
        self.move_backward_pushButton.setIconSize(QtCore.QSize(30, 30))
        self.move_backward_pushButton.setObjectName("move_backward_pushButton")
        self.gridLayout_12.addWidget(self.move_backward_pushButton, 0, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem, 0, 1, 1, 1)
        self.move_forward_pushButton = QtWidgets.QPushButton(self.statistics_content_WidgetPage)
        self.move_forward_pushButton.setStyleSheet("QPushButton {\n"
"    border: solid;\n"
"    border-color: #5647ae;\n"
"    border-width: 3px;\n"
"    border-radius: 15px;\n"
"    color: #f0f0f0;\n"
"    background-color: rgba(0,0,0,0);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgba( 86, 71, 174, 0.16)\n"
"}")
        self.move_forward_pushButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../img/forward-fill.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.move_forward_pushButton.setIcon(icon2)
        self.move_forward_pushButton.setIconSize(QtCore.QSize(30, 30))
        self.move_forward_pushButton.setObjectName("move_forward_pushButton")
        self.gridLayout_12.addWidget(self.move_forward_pushButton, 0, 3, 1, 1)
        self.bar_graph_stackedWidget = QtWidgets.QStackedWidget(self.statistics_content_WidgetPage)
        self.bar_graph_stackedWidget.setObjectName("bar_graph_stackedWidget")
        self.day = QtWidgets.QWidget()
        self.day.setObjectName("day")
        self.bar_graph_stackedWidget.addWidget(self.day)
        self.week = QtWidgets.QWidget()
        self.week.setObjectName("week")
        self.bar_graph_stackedWidget.addWidget(self.week)
        self.month = QtWidgets.QWidget()
        self.month.setObjectName("month")
        self.bar_graph_stackedWidget.addWidget(self.month)
        self.gridLayout_12.addWidget(self.bar_graph_stackedWidget, 1, 0, 1, 4)
        self.content_stackedWidget.addWidget(self.statistics_content_WidgetPage)
        self.Settings_content_WidgetPage = QtWidgets.QWidget()
        self.Settings_content_WidgetPage.setStyleSheet("QScrollBar:vertical{\n"
"border: none;\n"
"width:6px;\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical{\n"
"background-color: #9e9e9e;\n"
"border-radius:3px;\n"
"margin-top: 15px;\n"
"margin-bottom: 15px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical,\n"
"QScrollBar::sub-line:vertical {\n"
"    height: 0;\n"
"    width: 0;\n"
"}\n"
"\n"
"\n"
"")
        self.Settings_content_WidgetPage.setObjectName("Settings_content_WidgetPage")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.Settings_content_WidgetPage)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setSpacing(0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.scrollArea = QtWidgets.QScrollArea(self.Settings_content_WidgetPage)
        self.scrollArea.setStyleSheet("")
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -331, 714, 1204))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.settings_content = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.settings_content.setMinimumSize(QtCore.QSize(0, 0))
        self.settings_content.setStyleSheet("QSlider:horizontal {\n"
"height: 20px;\n"
"margin: 2px 0;\n"
"}\n"
"\n"
"QSlider::groove:horizontal {\n"
"    background: #9e9e9e;\n"
"    height: 4px; \n"
"    border-radius: 1px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: #5647ae;\n"
"    heigth: 15px;\n"
"    width: 15px;\n"
"    margin: -5px 0; \n"
"    border-radius: 7px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"        stop:0 #5647ae, /* Color on the left */\n"
"        stop:1 #5647ae  /* Color on the right */\n"
"    );\n"
"}\n"
"\n"
"QSlider::add-page:horizontal {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"        stop:0 #9e9e9e, /* Color on the left */\n"
"        stop:1 #9e9e9e  /* Color on the right */\n"
"    );\n"
"}")
        self.settings_content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.settings_content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.settings_content.setObjectName("settings_content")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.settings_content)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.timer_content = QtWidgets.QFrame(self.settings_content)
        self.timer_content.setMaximumSize(QtCore.QSize(16777215, 375))
        self.timer_content.setStyleSheet("color: white;")
        self.timer_content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.timer_content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.timer_content.setObjectName("timer_content")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.timer_content)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 30)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.short_break_duration_label = QtWidgets.QLabel(self.timer_content)
        self.short_break_duration_label.setMinimumSize(QtCore.QSize(204, 59))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.short_break_duration_label.setFont(font)
        self.short_break_duration_label.setStyleSheet("")
        self.short_break_duration_label.setObjectName("short_break_duration_label")
        self.gridLayout_7.addWidget(self.short_break_duration_label, 3, 0, 1, 1)
        self.short_break_duration_horizontalSlider = QtWidgets.QSlider(self.timer_content)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.short_break_duration_horizontalSlider.setFont(font)
        self.short_break_duration_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.short_break_duration_horizontalSlider.setObjectName("short_break_duration_horizontalSlider")
        self.gridLayout_7.addWidget(self.short_break_duration_horizontalSlider, 4, 0, 1, 3)
        self.show_long_break_duration_label = QtWidgets.QLabel(self.timer_content)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.show_long_break_duration_label.setFont(font)
        self.show_long_break_duration_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.show_long_break_duration_label.setStyleSheet("#show_long_break_duration_label {\n"
"color: #9e9e9e;\n"
"}")
        self.show_long_break_duration_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.show_long_break_duration_label.setObjectName("show_long_break_duration_label")
        self.gridLayout_7.addWidget(self.show_long_break_duration_label, 5, 2, 1, 1)
        self.settings_timer_label = QtWidgets.QLabel(self.timer_content)
        self.settings_timer_label.setMaximumSize(QtCore.QSize(70, 30))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(18)
        self.settings_timer_label.setFont(font)
        self.settings_timer_label.setStyleSheet("")
        self.settings_timer_label.setObjectName("settings_timer_label")
        self.gridLayout_7.addWidget(self.settings_timer_label, 0, 0, 1, 1)
        self.pomodoro_before_long_break_label = QtWidgets.QLabel(self.timer_content)
        self.pomodoro_before_long_break_label.setMinimumSize(QtCore.QSize(204, 59))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.pomodoro_before_long_break_label.setFont(font)
        self.pomodoro_before_long_break_label.setStyleSheet("")
        self.pomodoro_before_long_break_label.setObjectName("pomodoro_before_long_break_label")
        self.gridLayout_7.addWidget(self.pomodoro_before_long_break_label, 7, 0, 1, 1)
        self.long_break_duration_horizontalSlider = QtWidgets.QSlider(self.timer_content)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.long_break_duration_horizontalSlider.setFont(font)
        self.long_break_duration_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.long_break_duration_horizontalSlider.setObjectName("long_break_duration_horizontalSlider")
        self.gridLayout_7.addWidget(self.long_break_duration_horizontalSlider, 6, 0, 1, 3)
        self.long_break_duration_label = QtWidgets.QLabel(self.timer_content)
        self.long_break_duration_label.setMinimumSize(QtCore.QSize(204, 59))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.long_break_duration_label.setFont(font)
        self.long_break_duration_label.setStyleSheet("")
        self.long_break_duration_label.setObjectName("long_break_duration_label")
        self.gridLayout_7.addWidget(self.long_break_duration_label, 5, 0, 1, 1)
        self.show_short_break_duration_label = QtWidgets.QLabel(self.timer_content)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.show_short_break_duration_label.setFont(font)
        self.show_short_break_duration_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.show_short_break_duration_label.setStyleSheet("#show_short_break_duration_label{\n"
"color: #9e9e9e;\n"
"}")
        self.show_short_break_duration_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.show_short_break_duration_label.setObjectName("show_short_break_duration_label")
        self.gridLayout_7.addWidget(self.show_short_break_duration_label, 3, 2, 1, 1)
        self.show_pomodoro_duration_label = QtWidgets.QLabel(self.timer_content)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.show_pomodoro_duration_label.setFont(font)
        self.show_pomodoro_duration_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.show_pomodoro_duration_label.setStyleSheet("#show_pomodoro_duration_label {\n"
"color: #9e9e9e;\n"
"}")
        self.show_pomodoro_duration_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.show_pomodoro_duration_label.setObjectName("show_pomodoro_duration_label")
        self.gridLayout_7.addWidget(self.show_pomodoro_duration_label, 1, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem1, 7, 1, 1, 1)
        self.pomodoro_before_long_break_spinBox = QtWidgets.QSpinBox(self.timer_content)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.pomodoro_before_long_break_spinBox.setFont(font)
        self.pomodoro_before_long_break_spinBox.setStyleSheet("color: white;")
        self.pomodoro_before_long_break_spinBox.setObjectName("pomodoro_before_long_break_spinBox")
        self.gridLayout_7.addWidget(self.pomodoro_before_long_break_spinBox, 7, 2, 1, 1)
        self.pomodoro_duration_label = QtWidgets.QLabel(self.timer_content)
        self.pomodoro_duration_label.setMinimumSize(QtCore.QSize(204, 59))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.pomodoro_duration_label.setFont(font)
        self.pomodoro_duration_label.setStyleSheet("")
        self.pomodoro_duration_label.setObjectName("pomodoro_duration_label")
        self.gridLayout_7.addWidget(self.pomodoro_duration_label, 1, 0, 1, 1)
        self.pomodoro_duration_horizontalSlider = QtWidgets.QSlider(self.timer_content)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pomodoro_duration_horizontalSlider.setFont(font)
        self.pomodoro_duration_horizontalSlider.setStyleSheet("QSlider:horizontal {\n"
"height: 20px;\n"
"margin: 2px 0;\n"
"}\n"
"\n"
"QSlider::groove:horizontal {\n"
"    background: #9e9e9e;\n"
"    height: 4px; \n"
"    border-radius: 1px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: #5647ae;\n"
"    heigth: 15px;\n"
"    width: 15px;\n"
"    margin: -5px 0; \n"
"    border-radius: 7px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"        stop:0 #5647ae, /* Color on the left */\n"
"        stop:1 #5647ae  /* Color on the right */\n"
"    );\n"
"}\n"
"\n"
"QSlider::add-page:horizontal {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"        stop:0 #9e9e9e, /* Color on the left */\n"
"        stop:1 #9e9e9e  /* Color on the right */\n"
"    );\n"
"}")
        self.pomodoro_duration_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.pomodoro_duration_horizontalSlider.setObjectName("pomodoro_duration_horizontalSlider")
        self.gridLayout_7.addWidget(self.pomodoro_duration_horizontalSlider, 2, 0, 1, 3)
        self.verticalLayout_3.addWidget(self.timer_content)
        self.sound_content = QtWidgets.QFrame(self.settings_content)
        self.sound_content.setMaximumSize(QtCore.QSize(16777215, 350))
        self.sound_content.setStyleSheet("color: white;")
        self.sound_content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.sound_content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sound_content.setObjectName("sound_content")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.sound_content)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 30)
        self.gridLayout_9.setHorizontalSpacing(6)
        self.gridLayout_9.setVerticalSpacing(0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.end_break_sound_comboBox = QtWidgets.QComboBox(self.sound_content)
        self.end_break_sound_comboBox.setObjectName("end_break_sound_comboBox")
        self.gridLayout_9.addWidget(self.end_break_sound_comboBox, 6, 2, 1, 1)
        self.end_break_sound_label = QtWidgets.QLabel(self.sound_content)
        self.end_break_sound_label.setMinimumSize(QtCore.QSize(204, 59))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.end_break_sound_label.setFont(font)
        self.end_break_sound_label.setStyleSheet("")
        self.end_break_sound_label.setObjectName("end_break_sound_label")
        self.gridLayout_9.addWidget(self.end_break_sound_label, 6, 0, 1, 1)
        self.switch_placeholder = QtWidgets.QFrame(self.sound_content)
        self.switch_placeholder.setMaximumSize(QtCore.QSize(16777215, 50))
        self.switch_placeholder.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.switch_placeholder.setFrameShadow(QtWidgets.QFrame.Raised)
        self.switch_placeholder.setObjectName("switch_placeholder")
        self.gridLayout_9.addWidget(self.switch_placeholder, 1, 2, 1, 1)
        self.lower_volume_label = QtWidgets.QLabel(self.sound_content)
        self.lower_volume_label.setMaximumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.lower_volume_label.setFont(font)
        self.lower_volume_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lower_volume_label.setStyleSheet("#lower_volume_label {\n"
"color: #9e9e9e;\n"
"}")
        self.lower_volume_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lower_volume_label.setObjectName("lower_volume_label")
        self.gridLayout_9.addWidget(self.lower_volume_label, 3, 0, 1, 1)
        self.ticking_volume_horizontalSlider = QtWidgets.QSlider(self.sound_content)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.ticking_volume_horizontalSlider.setFont(font)
        self.ticking_volume_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.ticking_volume_horizontalSlider.setObjectName("ticking_volume_horizontalSlider")
        self.gridLayout_9.addWidget(self.ticking_volume_horizontalSlider, 4, 0, 1, 3)
        self.ticking_sound_label = QtWidgets.QLabel(self.sound_content)
        self.ticking_sound_label.setMinimumSize(QtCore.QSize(204, 59))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.ticking_sound_label.setFont(font)
        self.ticking_sound_label.setStyleSheet("")
        self.ticking_sound_label.setObjectName("ticking_sound_label")
        self.gridLayout_9.addWidget(self.ticking_sound_label, 1, 0, 1, 1)
        self.ticking_volume_label = QtWidgets.QLabel(self.sound_content)
        self.ticking_volume_label.setMinimumSize(QtCore.QSize(204, 59))
        self.ticking_volume_label.setMaximumSize(QtCore.QSize(204, 59))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.ticking_volume_label.setFont(font)
        self.ticking_volume_label.setStyleSheet("")
        self.ticking_volume_label.setObjectName("ticking_volume_label")
        self.gridLayout_9.addWidget(self.ticking_volume_label, 2, 0, 1, 1)
        self.start_break_sound_label = QtWidgets.QLabel(self.sound_content)
        self.start_break_sound_label.setMinimumSize(QtCore.QSize(204, 59))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.start_break_sound_label.setFont(font)
        self.start_break_sound_label.setStyleSheet("")
        self.start_break_sound_label.setObjectName("start_break_sound_label")
        self.gridLayout_9.addWidget(self.start_break_sound_label, 5, 0, 1, 1)
        self.settings_sound_label = QtWidgets.QLabel(self.sound_content)
        self.settings_sound_label.setMaximumSize(QtCore.QSize(70, 30))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(18)
        self.settings_sound_label.setFont(font)
        self.settings_sound_label.setStyleSheet("")
        self.settings_sound_label.setObjectName("settings_sound_label")
        self.gridLayout_9.addWidget(self.settings_sound_label, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem2, 3, 1, 1, 1)
        self.higher_volume_label = QtWidgets.QLabel(self.sound_content)
        self.higher_volume_label.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.higher_volume_label.setFont(font)
        self.higher_volume_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.higher_volume_label.setStyleSheet("#higher_volume_label {\n"
"color: #9e9e9e;\n"
"}")
        self.higher_volume_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.higher_volume_label.setObjectName("higher_volume_label")
        self.gridLayout_9.addWidget(self.higher_volume_label, 3, 2, 1, 1)
        self.start_break_sound_comboBox = QtWidgets.QComboBox(self.sound_content)
        self.start_break_sound_comboBox.setObjectName("start_break_sound_comboBox")
        self.gridLayout_9.addWidget(self.start_break_sound_comboBox, 5, 2, 1, 1)
        self.verticalLayout_3.addWidget(self.sound_content)
        self.desktop_content = QtWidgets.QFrame(self.settings_content)
        self.desktop_content.setStyleSheet("color: white;")
        self.desktop_content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.desktop_content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.desktop_content.setObjectName("desktop_content")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.desktop_content)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 30)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.dark_mode_lsbel = QtWidgets.QLabel(self.desktop_content)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.dark_mode_lsbel.setFont(font)
        self.dark_mode_lsbel.setStyleSheet("")
        self.dark_mode_lsbel.setObjectName("dark_mode_lsbel")
        self.gridLayout_10.addWidget(self.dark_mode_lsbel, 1, 0, 1, 1)
        self.about_label = QtWidgets.QLabel(self.desktop_content)
        self.about_label.setMinimumSize(QtCore.QSize(204, 59))
        self.about_label.setMaximumSize(QtCore.QSize(90, 30))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(18)
        self.about_label.setFont(font)
        self.about_label.setStyleSheet("")
        self.about_label.setObjectName("about_label")
        self.gridLayout_10.addWidget(self.about_label, 3, 0, 1, 1)
        self.switch_placeholder_3 = QtWidgets.QFrame(self.desktop_content)
        self.switch_placeholder_3.setMinimumSize(QtCore.QSize(72, 50))
        self.switch_placeholder_3.setMaximumSize(QtCore.QSize(72, 50))
        self.switch_placeholder_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.switch_placeholder_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.switch_placeholder_3.setObjectName("switch_placeholder_3")
        self.gridLayout_10.addWidget(self.switch_placeholder_3, 2, 2, 1, 1)
        self.software_description_label = QtWidgets.QTextEdit(self.desktop_content)
        self.software_description_label.setMinimumSize(QtCore.QSize(0, 200))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.software_description_label.setFont(font)
        self.software_description_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.software_description_label.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.software_description_label.setLineWrapMode(QtWidgets.QTextEdit.WidgetWidth)
        self.software_description_label.setObjectName("software_description_label")
        self.gridLayout_10.addWidget(self.software_description_label, 4, 0, 1, 3)
        self.switch_placeholder_2 = QtWidgets.QFrame(self.desktop_content)
        self.switch_placeholder_2.setMinimumSize(QtCore.QSize(0, 50))
        self.switch_placeholder_2.setMaximumSize(QtCore.QSize(72, 50))
        self.switch_placeholder_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.switch_placeholder_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.switch_placeholder_2.setObjectName("switch_placeholder_2")
        self.gridLayout_10.addWidget(self.switch_placeholder_2, 1, 2, 1, 1)
        self.settings_desktop_label = QtWidgets.QLabel(self.desktop_content)
        self.settings_desktop_label.setMaximumSize(QtCore.QSize(90, 30))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(18)
        self.settings_desktop_label.setFont(font)
        self.settings_desktop_label.setStyleSheet("")
        self.settings_desktop_label.setObjectName("settings_desktop_label")
        self.gridLayout_10.addWidget(self.settings_desktop_label, 0, 0, 1, 1)
        self.notification_label = QtWidgets.QLabel(self.desktop_content)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.notification_label.setFont(font)
        self.notification_label.setStyleSheet("")
        self.notification_label.setObjectName("notification_label")
        self.gridLayout_10.addWidget(self.notification_label, 2, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem3, 1, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.desktop_content)
        self.verticalLayout_2.addWidget(self.settings_content)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_8.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.content_stackedWidget.addWidget(self.Settings_content_WidgetPage)
        self.gridLayout_11.addWidget(self.content_stackedWidget, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.content_frame, 2, 0, 1, 1)
        self.horizontalLayout.addWidget(self.managment_tool_frame)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.content_stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Pomodorodex"))
        self.change_modus_label.setText(_translate("MainWindow", "Pomodoro"))
        self.timer_label.setText(_translate("MainWindow", "25:00"))
        self.Task_pushButton.setText(_translate("MainWindow", "Task"))
        self.statistics_pushButton.setText(_translate("MainWindow", "Statistics"))
        self.settings_pushButton.setText(_translate("MainWindow", "Settings"))
        self.save_pushButton.setText(_translate("MainWindow", "Save"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "  Define Your Task"))
        self.clear_pushButton.setText(_translate("MainWindow", "Clear"))
        self.day_week_month_label.setText(_translate("MainWindow", "Day"))
        self.short_break_duration_label.setText(_translate("MainWindow", "Short Break duration"))
        self.show_long_break_duration_label.setText(_translate("MainWindow", "15 min"))
        self.settings_timer_label.setText(_translate("MainWindow", "Timer"))
        self.pomodoro_before_long_break_label.setText(_translate("MainWindow", "Pomodoro before long break"))
        self.long_break_duration_label.setText(_translate("MainWindow", "Long Break duration"))
        self.show_short_break_duration_label.setText(_translate("MainWindow", "5 min"))
        self.show_pomodoro_duration_label.setText(_translate("MainWindow", "25 min"))
        self.pomodoro_duration_label.setText(_translate("MainWindow", "Pomodoro duration"))
        self.end_break_sound_label.setText(_translate("MainWindow", "End Break Sound"))
        self.lower_volume_label.setText(_translate("MainWindow", "-"))
        self.ticking_sound_label.setText(_translate("MainWindow", "Ticking Sound"))
        self.ticking_volume_label.setText(_translate("MainWindow", "Ticking Volume"))
        self.start_break_sound_label.setText(_translate("MainWindow", "Start Break Sound"))
        self.settings_sound_label.setText(_translate("MainWindow", "Sound"))
        self.higher_volume_label.setText(_translate("MainWindow", "+"))
        self.dark_mode_lsbel.setText(_translate("MainWindow", "Dark Mode"))
        self.about_label.setText(_translate("MainWindow", "About"))
        self.software_description_label.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Roboto\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans Serif\';\">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed volutpat risus non tellus faucibus condimentum. Aliquam sit amet pretium risus, ut vehicula erat. Aliquam pulvinar neque sollicitudin suscipit feugiat. Aenean suscipit quam a dignissim efficitur. Integer id lacus vitae diam mollis mattis vitae sit amet lacus. Fusce rutrum, metus eu condimentum pharetra, est eros porta nisl, vel feugiat nibh ex id sem. Donec condimentum suscipit urna at tempor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec dignissim enim sit amet vestibulum lacinia. Etiam dui erat, tristique sit amet laoreet eget, fermentum in nisl. Donec sollicitudin fringilla neque nec molestie. </span></p></body></html>"))
        self.settings_desktop_label.setText(_translate("MainWindow", "Desktop"))
        self.notification_label.setText(_translate("MainWindow", "Notification"))


def main():
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
